name: Build and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

permissions:
  contents: read

jobs:
  build:
    name: Build and test with Xcode ${{ matrix.xcode.version }} on ${{ matrix.xcode.os }}
    runs-on: ${{ matrix.xcode.os }}

    strategy:
      matrix:
        xcode: 
          - { os: macos-12, version: "14.1" }

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/workflows/templates/setup-ios
    - name: Xcode build for ${{ matrix.environment }}
      run: make swift-build
    - name: Upload build log Artifact
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: xcodebuild-logs
        path: |
          ./WebSwiftUI/Reports/*_Build.log
        if-no-files-found: ignore
        retention-days: 14

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode.version }}.app

  info:
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Output Information
      uses: ./.github/workflows/templates/output-info
