name: Build and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE

permissions:
  contents: read

jobs:
  run: 
    name: Build and test with Xcode ${{ matrix.xcode.version }} on ${{ matrix.xcode.os }}
    runs-on: ${{ matrix.xcode.os }}
    strategy:
      matrix:
        xcode: 
          - { os: macos-latest, version: "14.0" }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show Versions
        run: |
          xcodebuild -version
          swift --version
          swift package --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swfit teset -v -c release
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode.version }}.app
